var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(app)/demo/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__4489c01f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b9a0874._.js")
R.c("server/chunks/ssr/_a857911f._.js")
R.c("server/chunks/ssr/[root-of-the-server]__2dfaea0f._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1690ee0d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_77ec7569._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__a1ff59be._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_(app)_demo_page_actions_c92e2a71.js")
R.m(8900834)
module.exports=R.m(8900834).exports
