var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(app)/settings/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__cd46764c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b9a0874._.js")
R.c("server/chunks/ssr/_27d9624c._.js")
R.c("server/chunks/ssr/[root-of-the-server]__16ed5cfd._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1690ee0d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_77ec7569._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__a1ff59be._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_(app)_settings_page_actions_66a40f1b.js")
R.m(643001)
module.exports=R.m(643001).exports
